2025-05-16 15:06:30,008 - root - INFO - 使用的 ChromeDriver 路径: D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\Base\utils\chromedriver.exe
2025-05-16 15:06:30,232 - root - INFO - Test case test_add_sales_plan started at 2025-05-16 15:06:30.232141
2025-05-16 15:06:31,334 - root - INFO - 开始登录操作
2025-05-16 15:06:35,307 - root - INFO - 已打开登录页面
2025-05-16 15:06:35,310 - root - ERROR - 登录过程中出现错误: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF7428A2775+28773]
	(No symbol) [0x00007FF74280AFB0]
	(No symbol) [0x00007FF7426A552A]
	(No symbol) [0x00007FF74267F2B5]
	(No symbol) [0x00007FF742725FD7]
	(No symbol) [0x00007FF74273EA92]
	(No symbol) [0x00007FF74271ED43]
	(No symbol) [0x00007FF7426EA548]
	(No symbol) [0x00007FF7426EB6B1]
	GetHandleVerifier [0x00007FF742BCF45D+3358029]
	GetHandleVerifier [0x00007FF742BE430D+3443709]
	GetHandleVerifier [0x00007FF742BD83FD+3394797]
	GetHandleVerifier [0x00007FF74296929B+842635]
	(No symbol) [0x00007FF74281654F]
	(No symbol) [0x00007FF742811FA4]
	(No symbol) [0x00007FF74281213D]
	(No symbol) [0x00007FF742801629]
	BaseThreadInitThunk [0x00007FFD80A67614+20]
	RtlUserThreadStart [0x00007FFD817226A1+33]
Traceback (most recent call last):
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\PageObject\login_page.py", line 144, in login
    self.send_keys(*self.USERNAME_INPUT, username)
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\Base\base_page.py", line 23, in send_keys
    element = self.find_element(by, value, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\Base\base_page.py", line 14, in find_element
    return WebDriverWait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 137, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 633, in _predicate
    target = driver.find_element(*target)  # grab element at locator
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 917, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF7428A2775+28773]
	(No symbol) [0x00007FF74280AFB0]
	(No symbol) [0x00007FF7426A552A]
	(No symbol) [0x00007FF74267F2B5]
	(No symbol) [0x00007FF742725FD7]
	(No symbol) [0x00007FF74273EA92]
	(No symbol) [0x00007FF74271ED43]
	(No symbol) [0x00007FF7426EA548]
	(No symbol) [0x00007FF7426EB6B1]
	GetHandleVerifier [0x00007FF742BCF45D+3358029]
	GetHandleVerifier [0x00007FF742BE430D+3443709]
	GetHandleVerifier [0x00007FF742BD83FD+3394797]
	GetHandleVerifier [0x00007FF74296929B+842635]
	(No symbol) [0x00007FF74281654F]
	(No symbol) [0x00007FF742811FA4]
	(No symbol) [0x00007FF74281213D]
	(No symbol) [0x00007FF742801629]
	BaseThreadInitThunk [0x00007FFD80A67614+20]
	RtlUserThreadStart [0x00007FFD817226A1+33]

2025-05-16 15:06:35,328 - root - INFO - 开始登录操作
2025-05-16 15:06:35,336 - root - ERROR - 登录过程中出现错误: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF7428A2775+28773]
	(No symbol) [0x00007FF74280AFB0]
	(No symbol) [0x00007FF7426A552A]
	(No symbol) [0x00007FF74267F2B5]
	(No symbol) [0x00007FF742725FD7]
	(No symbol) [0x00007FF74273EA92]
	(No symbol) [0x00007FF74271ED43]
	(No symbol) [0x00007FF7426EA548]
	(No symbol) [0x00007FF7426EB6B1]
	GetHandleVerifier [0x00007FF742BCF45D+3358029]
	GetHandleVerifier [0x00007FF742BE430D+3443709]
	GetHandleVerifier [0x00007FF742BD83FD+3394797]
	GetHandleVerifier [0x00007FF74296929B+842635]
	(No symbol) [0x00007FF74281654F]
	(No symbol) [0x00007FF742811FA4]
	(No symbol) [0x00007FF74281213D]
	(No symbol) [0x00007FF742801629]
	BaseThreadInitThunk [0x00007FFD80A67614+20]
	RtlUserThreadStart [0x00007FFD817226A1+33]
Traceback (most recent call last):
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\PageObject\login_page.py", line 142, in login
    self.driver.get(ERP_URL)
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 473, in get
    self.execute(Command.GET, {"url": url})
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF7428A2775+28773]
	(No symbol) [0x00007FF74280AFB0]
	(No symbol) [0x00007FF7426A552A]
	(No symbol) [0x00007FF74267F2B5]
	(No symbol) [0x00007FF742725FD7]
	(No symbol) [0x00007FF74273EA92]
	(No symbol) [0x00007FF74271ED43]
	(No symbol) [0x00007FF7426EA548]
	(No symbol) [0x00007FF7426EB6B1]
	GetHandleVerifier [0x00007FF742BCF45D+3358029]
	GetHandleVerifier [0x00007FF742BE430D+3443709]
	GetHandleVerifier [0x00007FF742BD83FD+3394797]
	GetHandleVerifier [0x00007FF74296929B+842635]
	(No symbol) [0x00007FF74281654F]
	(No symbol) [0x00007FF742811FA4]
	(No symbol) [0x00007FF74281213D]
	(No symbol) [0x00007FF742801629]
	BaseThreadInitThunk [0x00007FFD80A67614+20]
	RtlUserThreadStart [0x00007FFD817226A1+33]

2025-05-16 15:06:35,338 - root - INFO - 开始登录操作
2025-05-16 15:06:35,340 - root - ERROR - 登录过程中出现错误: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF7428A2775+28773]
	(No symbol) [0x00007FF74280AFB0]
	(No symbol) [0x00007FF7426A552A]
	(No symbol) [0x00007FF74267F2B5]
	(No symbol) [0x00007FF742725FD7]
	(No symbol) [0x00007FF74273EA92]
	(No symbol) [0x00007FF74271ED43]
	(No symbol) [0x00007FF7426EA548]
	(No symbol) [0x00007FF7426EB6B1]
	GetHandleVerifier [0x00007FF742BCF45D+3358029]
	GetHandleVerifier [0x00007FF742BE430D+3443709]
	GetHandleVerifier [0x00007FF742BD83FD+3394797]
	GetHandleVerifier [0x00007FF74296929B+842635]
	(No symbol) [0x00007FF74281654F]
	(No symbol) [0x00007FF742811FA4]
	(No symbol) [0x00007FF74281213D]
	(No symbol) [0x00007FF742801629]
	BaseThreadInitThunk [0x00007FFD80A67614+20]
	RtlUserThreadStart [0x00007FFD817226A1+33]
Traceback (most recent call last):
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\PageObject\login_page.py", line 142, in login
    self.driver.get(ERP_URL)
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 473, in get
    self.execute(Command.GET, {"url": url})
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF7428A2775+28773]
	(No symbol) [0x00007FF74280AFB0]
	(No symbol) [0x00007FF7426A552A]
	(No symbol) [0x00007FF74267F2B5]
	(No symbol) [0x00007FF742725FD7]
	(No symbol) [0x00007FF74273EA92]
	(No symbol) [0x00007FF74271ED43]
	(No symbol) [0x00007FF7426EA548]
	(No symbol) [0x00007FF7426EB6B1]
	GetHandleVerifier [0x00007FF742BCF45D+3358029]
	GetHandleVerifier [0x00007FF742BE430D+3443709]
	GetHandleVerifier [0x00007FF742BD83FD+3394797]
	GetHandleVerifier [0x00007FF74296929B+842635]
	(No symbol) [0x00007FF74281654F]
	(No symbol) [0x00007FF742811FA4]
	(No symbol) [0x00007FF74281213D]
	(No symbol) [0x00007FF742801629]
	BaseThreadInitThunk [0x00007FFD80A67614+20]
	RtlUserThreadStart [0x00007FFD817226A1+33]

2025-05-16 15:06:35,342 - root - INFO - 开始登录操作
2025-05-16 15:06:35,344 - root - ERROR - 登录过程中出现错误: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF7428A2775+28773]
	(No symbol) [0x00007FF74280AFB0]
	(No symbol) [0x00007FF7426A552A]
	(No symbol) [0x00007FF74267F2B5]
	(No symbol) [0x00007FF742725FD7]
	(No symbol) [0x00007FF74273EA92]
	(No symbol) [0x00007FF74271ED43]
	(No symbol) [0x00007FF7426EA548]
	(No symbol) [0x00007FF7426EB6B1]
	GetHandleVerifier [0x00007FF742BCF45D+3358029]
	GetHandleVerifier [0x00007FF742BE430D+3443709]
	GetHandleVerifier [0x00007FF742BD83FD+3394797]
	GetHandleVerifier [0x00007FF74296929B+842635]
	(No symbol) [0x00007FF74281654F]
	(No symbol) [0x00007FF742811FA4]
	(No symbol) [0x00007FF74281213D]
	(No symbol) [0x00007FF742801629]
	BaseThreadInitThunk [0x00007FFD80A67614+20]
	RtlUserThreadStart [0x00007FFD817226A1+33]
Traceback (most recent call last):
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\PageObject\login_page.py", line 142, in login
    self.driver.get(ERP_URL)
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 473, in get
    self.execute(Command.GET, {"url": url})
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF7428A2775+28773]
	(No symbol) [0x00007FF74280AFB0]
	(No symbol) [0x00007FF7426A552A]
	(No symbol) [0x00007FF74267F2B5]
	(No symbol) [0x00007FF742725FD7]
	(No symbol) [0x00007FF74273EA92]
	(No symbol) [0x00007FF74271ED43]
	(No symbol) [0x00007FF7426EA548]
	(No symbol) [0x00007FF7426EB6B1]
	GetHandleVerifier [0x00007FF742BCF45D+3358029]
	GetHandleVerifier [0x00007FF742BE430D+3443709]
	GetHandleVerifier [0x00007FF742BD83FD+3394797]
	GetHandleVerifier [0x00007FF74296929B+842635]
	(No symbol) [0x00007FF74281654F]
	(No symbol) [0x00007FF742811FA4]
	(No symbol) [0x00007FF74281213D]
	(No symbol) [0x00007FF742801629]
	BaseThreadInitThunk [0x00007FFD80A67614+20]
	RtlUserThreadStart [0x00007FFD817226A1+33]

2025-05-16 15:06:35,348 - root - INFO - 开始登录操作
2025-05-16 15:06:35,349 - root - ERROR - 登录过程中出现错误: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF7428A2775+28773]
	(No symbol) [0x00007FF74280AFB0]
	(No symbol) [0x00007FF7426A552A]
	(No symbol) [0x00007FF74267F2B5]
	(No symbol) [0x00007FF742725FD7]
	(No symbol) [0x00007FF74273EA92]
	(No symbol) [0x00007FF74271ED43]
	(No symbol) [0x00007FF7426EA548]
	(No symbol) [0x00007FF7426EB6B1]
	GetHandleVerifier [0x00007FF742BCF45D+3358029]
	GetHandleVerifier [0x00007FF742BE430D+3443709]
	GetHandleVerifier [0x00007FF742BD83FD+3394797]
	GetHandleVerifier [0x00007FF74296929B+842635]
	(No symbol) [0x00007FF74281654F]
	(No symbol) [0x00007FF742811FA4]
	(No symbol) [0x00007FF74281213D]
	(No symbol) [0x00007FF742801629]
	BaseThreadInitThunk [0x00007FFD80A67614+20]
	RtlUserThreadStart [0x00007FFD817226A1+33]
Traceback (most recent call last):
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\PageObject\login_page.py", line 142, in login
    self.driver.get(ERP_URL)
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 473, in get
    self.execute(Command.GET, {"url": url})
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "D:\gmj\workSpaces\workSpaces_pycharm\autoTest4\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF7428A2775+28773]
	(No symbol) [0x00007FF74280AFB0]
	(No symbol) [0x00007FF7426A552A]
	(No symbol) [0x00007FF74267F2B5]
	(No symbol) [0x00007FF742725FD7]
	(No symbol) [0x00007FF74273EA92]
	(No symbol) [0x00007FF74271ED43]
	(No symbol) [0x00007FF7426EA548]
	(No symbol) [0x00007FF7426EB6B1]
	GetHandleVerifier [0x00007FF742BCF45D+3358029]
	GetHandleVerifier [0x00007FF742BE430D+3443709]
	GetHandleVerifier [0x00007FF742BD83FD+3394797]
	GetHandleVerifier [0x00007FF74296929B+842635]
	(No symbol) [0x00007FF74281654F]
	(No symbol) [0x00007FF742811FA4]
	(No symbol) [0x00007FF74281213D]
	(No symbol) [0x00007FF742801629]
	BaseThreadInitThunk [0x00007FFD80A67614+20]
	RtlUserThreadStart [0x00007FFD817226A1+33]

2025-05-16 15:06:35,350 - root - ERROR - 验证码识别失败次数达到上限，登录失败
2025-05-16 15:06:35,444 - root - INFO - Test case test_add_sales_plan ended at 2025-05-16 15:06:35.444006
